/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Computation */

#ifndef _Included_Computation
#define _Included_Computation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Computation
 * Method:    gcdOf
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_Computation_gcdOf
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     Computation
 * Method:    sumOfSquares
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_Computation_sumOfSquares
  (JNIEnv *, jclass, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
