/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LegacyQE */

#ifndef _Included_LegacyQE
#define _Included_LegacyQE
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LegacyQE
 * Method:    realRoots
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_LegacyQE_realRoots
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
